site_name: Blueberry Hill Farm
site_url: https://blueberryhillfarm.me
theme:
  name: material
  custom_dir: overrides
  logo: favicon.ico
  favicon: favicon.ico
  palette:
    primary: amber
    accent: indigo
plugins: []
extra_css:
  - stylesheets/extra.css
